# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options


class TestSmoketest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPage(self):
    self.driver.get("http://127.0.0.1:5500/cse270-Teton/teton/1.6/admin.html")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "username")))
    self.driver.find_element(By.ID, "username").send_keys("testing")
    self.driver.find_element(By.ID, "password").send_keys("testing")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".errorMessage")))
  
  def test_directoryPage(self):
    self.driver.get("http://127.0.0.1:5500/cse270-Teton/teton/1.6/directory.html")
    self.driver.find_element(By.ID, "directory-grid").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")))
    self.driver.find_element(By.ID, "directory-list").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")))
  
  def test_homePage(self):
    self.driver.get("http://127.0.0.1:5500/cse270-Teton/teton/1.6/index.html")
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".header-logo img")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".spotlight1")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".spotlight2")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Join Us!")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Join Us")))
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "fname")))
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_joinPage(self):
    self.driver.get("http://127.0.0.1:5500/cse270-Teton/teton/1.6/join.html")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "fname")))
    self.driver.find_element(By.NAME, "fname").send_keys("Testing")
    self.driver.find_element(By.NAME, "lname").send_keys("Testing")
    self.driver.find_element(By.NAME, "bizname").send_keys("Testing")
    self.driver.find_element(By.NAME, "biztitle").send_keys("owner")
    self.driver.find_element(By.NAME, "submit").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "email")))
  
